portApp/urls.py
from django.contrib import admin
from django.urls import path,include
from portfo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('portfo/',include('portfo.urls'))
]

portfo/urls.py
from django.contrib import admin
from django.urls import path,include
from portfo import views

app_name = 'portfo'

urlpatterns = [
    path('about/', views.about,name='about_me'),
    path('contact/',views.contact,name='contact'),
    path('get_value/',views.get_value,name='get_value'),
]

portfo/models.py
from django.db import models

# Create your models here.
class user(models.Model):
	email=models.EmailField(max_length=254)
	subject=models.CharField(max_length=254)
	text=models.CharField(max_length=400000)

portfo/forms.py
from django import forms

class UserForm(forms.Form):
	email=forms.EmailField(max_length=200)

portfo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import user

# Create your views here.
def index(request):
	return render(request,'portfo/index.html')
def about(request):
	return render(request,'portfo/about.html')

def contact(request):
	return render(request,'portfo/contact.html')

def get_value(request):
	if request.method=='POST':
		email=request.POST.get('email')
		sub=request.POST.get('subject')
		text=request.POST.get('textarea')
		use=user()
		use.email=email
		use.subject=sub
		use.text=text
		use.save()
	return render(request,'portfo/thankyou.html')

templates/portfo/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">
  
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

  <title>Title page</title>  

<link href="/static/portfo/main.3f6952e4.css" rel="stylesheet"></head>

<body class="">
<div id="site-border-left"></div>
<div id="site-border-right"></div>
<div id="site-border-top"></div>
<div id="site-border-bottom"></div>
 <!-- Add your content of header -->
<header>
  <nav class="navbar  navbar-fixed-top navbar-default">
    <div class="container">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav ">
          <li><a href="{% url 'index' %}" title="">01 : Home</a></li>
          <li><a href="{% url 'portfo:about_me' %}" title="">02 : About me</a></li>
          <li><a href="{% url 'portfo:contact' %}" title="">03 : Contact</a></li>
        </ul>


      </div> 
    </div>
  </nav>
</header>

<div class="section-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="section-container-spacer text-center">
            <h1 class="h2">02 : About me</h1>
          </div>
          
          <div class="row">
            <div class="col-md-10 col-md-offset-1">
              <div class="row">
                <div class="col-xs-12 col-md-6">
                  <h3>Python Developer</h3>
                  <p>I express myself as a Python developer.
                  Have a wide knowldge about many libraries like
                sklearn, Pandas, Numpy, matplotlib and much more
              .Also have some experience in backend development using Django and Flask.</p>
              <h3>Data Science and Machine Learning</h3>
                  <p>
                  Knows how to handle Data, preprocess and use it to make Machine Leaning models</p>
                  <h3>Web Developer</h3>
                  <p>Also have some hands on experience on Web development using HTML, CSS, JavaScript, jQuery, Bootstrap. And Backend using Django and Flask</p>
                  <p>Some projects are showcased on my github handle<a href="https://github.com/Mayurg6832" target="_blank" class="fa-icon">
                        <i class="fa fa-github"></i>
                      </a></p>

                </div>
                <div class="col-xs-12 col-md-6">
                  <img src="/static/port.jpg" class="img-responsive" alt="">
                </div>
              </div>
            </div>
          </div>
       </div>
      </div>
    </div>
  </div>


<script>
  document.addEventListener("DOMContentLoaded", function (event) {
     navActivePage();
  });
</script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID 

<script>
  (function (i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
      (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date(); a = s.createElement(o),
      m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-XXXXX-X', 'auto');
  ga('send', 'pageview');
</script>

--> <script type="text/javascript" src="/static/portfo/main.70a66962.js"></script></body>

</html>

templates/portfo/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">
  
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

  <title>Title page</title>  

<link href="/static/portfo/main.3f6952e4.css" rel="stylesheet"></head>

<body class="">
<div id="site-border-left"></div>
<div id="site-border-right"></div>
<div id="site-border-top"></div>
<div id="site-border-bottom"></div>
 <!-- Add your content of header -->
<header>
  <nav class="navbar  navbar-fixed-top navbar-default">
    <div class="container">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav ">
          <li><a href="{% url 'index' %}" title="">01 : Home</a></li>
          <li><a href="{% url 'portfo:about_me' %}" title="">02 : About me</a></li>
          <li><a href="{% url 'portfo:contact' %}" title="">03 : Contact</a></li>
        </ul>


      </div> 
    </div>
  </nav>
</header>

<div class="section-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="section-container-spacer text-center">
            <h1 class="h2">03 : Contact me</h1>
          </div>
          
          <div class="row">
            <div class="col-md-10 col-md-offset-1">
               <form action="{% url 'portfo:get_value' %}" class="reveal-content" method="post">
                {% csrf_token %}
                  <div class="row">
                    <div class="col-md-7">
                      <div class="form-group">
                        <input type="email" class="form-control" id="email" placeholder="Email" name="email">
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control" id="subject" placeholder="Subject" name="subject">
                      </div>
                      <div class="form-group">
                        <textarea class="form-control" rows="5" placeholder="Enter your message" name="textarea"></textarea>
                      </div>
                      <button type="submit" class="btn btn-default btn-lg">Send</button>
                    </div>
                    <div class="col-md-5 address-container">
                      <ul class="list-unstyled">
                        <li>
                          <span class="fa-icon">
                            <i class="fa fa-phone" aria-hidden="true"></i>
                          </span>
                          +91 8979821748
                        </li>
                        <li>
                          <span class="fa-icon">
                            <i class="fa fa-at" aria-hidden="true"></i>
                          </span>
                          Mayurg6832.mg@gmail.com
                        </li>
                        <li>
                          <span class="fa-icon">
                            <i class="fa fa fa-map-marker" aria-hidden="true"></i>
                          </span>
                          Kamla Nagar, Agra
                          Uttar Pradesh
                        </li>
                      </ul>
                      <h3>Follow me on social networks</h3>
                      <a href="https://www.facebook.com/mayur.goyal.6832" target="_blank" class="fa-icon">
                        <i class="fa fa-facebook"></i>
                      </a>
                      <a href="https://twitter.com/MayurGo75256817" target="_blank" class="fa-icon">
                        <i class="fa fa-twitter"></i>
                      </a>
                      <a href="https://www.linkedin.com/in/mayur-goyal-194816178/" target="_blank" class="fa-icon">
                        <i class="fa fa-linkedin"></i>
                      </a>
                      <a href="https://github.com/Mayurg6832" target="_blank" class="fa-icon">
                        <i class="fa fa-github"></i>
                      </a>

                    </div>
                  </div>
                </form>
            </div>

          </div>
         
       </div>
      </div>
    </div>
  </div>



<script>
  document.addEventListener("DOMContentLoaded", function (event) {
     navActivePage();
  });
</script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID 

<script>
  (function (i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
      (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date(); a = s.createElement(o),
      m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-XXXXX-X', 'auto');
  ga('send', 'pageview');
</script>

--> <script type="text/javascript" src="/static/portfo/main.70a66962.js"></script></body>

</html>

templates/portfo/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">
  
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
  <title>Title page</title>  

<link href="/static/portfo/main.3f6952e4.css" rel="stylesheet"></head>

<body class="minimal">
<div id="site-border-left"></div>
<div id="site-border-right"></div>
<div id="site-border-top"></div>
<div id="site-border-bottom"></div>
<!-- Add your content of header -->
<header>
  <nav class="navbar  navbar-fixed-top navbar-inverse">
    <div class="container">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav ">
          <li><a href="{% url 'index' %}" title="">01 : Home</a></li>
          <li><a href="{% url 'portfo:about_me' %}" title="">02 : About me</a></li>
          <li><a href="{% url 'portfo:contact' %}" title="">03 : Contact</a></li>
        </ul>


      </div> 
    </div>
  </nav>
</header>
<!-- Add your site or app content here -->
  <div class="hero-full-container background-image-container white-text-container" style="background-image: url('/static/portfo/assets/images/space.jpg')">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="hero-full-wrapper">
            <div class="text-content">
              <h1>Hello,<br>
                <span id="typed-strings">
                  <span>I'm Mayur Goyal</span>
                  <span>Python Developer</span>
                  <span>Your Digital Partner</span>
                </span>
                <span id="typed"></span>
              </h1>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<script>
  document.addEventListener("DOMContentLoaded", function (event) {
     type();
     movingBackgroundImage();
  });
</script>


<script type="text/javascript" src="/static/portfo/main.70a66962.js"></script></body>

</html>

templates/portfo/thankyou.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">
  
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

  <title>Title page</title>  

<link href="/static/portfo/main.3f6952e4.css" rel="stylesheet"></head>

<body class="">
<div id="site-border-left"></div>
<div id="site-border-right"></div>
<div id="site-border-top"></div>
<div id="site-border-bottom"></div>
 <!-- Add your content of header -->
<header>
  <nav class="navbar  navbar-fixed-top navbar-default">
    <div class="container">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav ">
          <li><a href="{% url 'index' %}" title="">01 : Home</a></li>
          <li><a href="{% url 'portfo:about_me' %}" title="">02 : About me</a></li>
          <li><a href="{% url 'portfo:contact' %}" title="">03 : Contact</a></li>
        </ul>


      </div> 
    </div>
  </nav>
</header>

<div class="section-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="section-container-spacer text-center">
            <h1 class="h2">03 : Contact me</h1>
          </div>
          
          <div class="row">
            <div class="col-md-10 col-md-offset-1">
               Thank you! I will get in touch with you shortly.
            </div>

          </div>
         
       </div>
      </div>
    </div>
  </div>



<script>
  document.addEventListener("DOMContentLoaded", function (event) {
     navActivePage();
  });
</script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID 

<script>
  (function (i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
      (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date(); a = s.createElement(o),
      m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-XXXXX-X', 'auto');
  ga('send', 'pageview');
</script>

--> <script type="text/javascript" src="/static/portfo/main.70a66962.js"></script></body>

</html>